version: "3.2"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F /dev/null
    volumes:
      - ./components:/usr/app/components
      - ./pages:/usr/app/pages
      - ./static:/usr/app/static
      - ./__tests__:/usr/app/__tests__
      - ./__tests__/ci__image_snapshots__:/usr/app/__tests__/__image_snapshots__
    ports:
      - "3001:3001"
