version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - ./__tests__/ci__image_snapshots__:/usr/app/__tests__/__image_snapshots__
      - /usr/app/node_modules
    ports:
      - "3001:3001"
