defaults: &defaults
  docker:
    - image: circleci/node:8.9.4-browsers

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: sudo npm install -g greenkeeper-lockfile@1

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run: npm run export
      - run: greenkeeper-lockfile-update

      - persist_to_workspace:
          root: .
          paths:
            - .next
            - out

  test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      # use ci snapshots for comparisons
      - run: rm -rf ~/project/__tests__/__image_snapshots__/ && cp -r ~/project/__tests__/ci__image_snapshots__/ ~/project/__tests__/__image_snapshots__/

      # run tests!
      - run: npm run test

      - run: sudo npm install -g greenkeeper-lockfile@1
      - run: greenkeeper-lockfile-upload

      # store artifacts, diffs from jest-image-snapshot
      - store_artifacts:
          path: ~/project/__tests__/__image_snapshots__/__diff_output__/
          destination: snapshots-diff

  deploy:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          command: |
            git config --global user.email "bot@circleci"
            git config --global user.name "CircleCI"
            git clone git@github.com:$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git -b gh-pages public
            cp -a out/. public/.
            cd public
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
