defaults: &defaults
  docker:
    - image: circleci/node:8.9.4-browsers

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: .
          paths: .next

  test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      # use ci snapshots for comparisons
      - run: rm -rf ~/project/__tests__/__image_snapshots__/ && cp -r ~/project/__tests__/ci__image_snapshots__/ ~/project/__tests__/__image_snapshots__/

      # run tests!
      - run: npm run test

      # store artifacts, diffs from jest-image-snapshot
      - store_artifacts:
          path: ~/project/__tests__/__image_snapshots__/__diff_output__/
          destination: snapshots-diff

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
