name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install --allow-scripts --frozen

      - name: Lint
        run: deno task lint

      - name: Check formatting
        run: deno task format:check

      - name: Check types
        run: deno task check

      - name: Build
        run: deno task build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
